platform :ios, '8.0'
target ‘XMG’ do

pod 'JPush', '~> 3.0.6'
pod 'Bugly', '~> 2.4.8'
pod 'SDWebImage', '~> 4.0.0’
pod 'SDAutoLayout', '~> 2.2.0'
pod 'IQKeyboardManager', '~> 5.0.3’
pod 'SDCycleScrollView', '~> 1.73'
pod 'MBProgressHUD', '~> 1.0.0’
pod 'AFNetworking', '~> 3.1.0'
pod 'MJRefresh', '~> 3.1.14'
pod 'YTKNetwork', '~> 2.0.4'
pod 'AMapLocation-NO-IDFA'

end
